theme: jekyll-theme-minimal
title: Matin Ghavamizadeh
description: Interested in Bayesian Machine Learning, Probabilistic Programming, and NLP. Recent UC Berkeley EECS and applied mathematics graduate.
logo: headshot.jpg
